[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Prevent Netlify from overly optimizing critical assets
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = false

[build.processing.js]
  bundle = true
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false

# Critical asset handling - prevent optimization that might break functionality
[[plugins]]
  package = "@netlify/plugin-local-install-core"

[plugins.inputs]
  mode = "copy"

# Global headers to preserve theme and functionality
[[headers]]
  for = "/*"
  [headers.values]
    X-Netlify-No-Transform = "true"
    Content-Security-Policy = "upgrade-insecure-requests"
    X-Content-Type-Options = "nosniff"

# Asset optimization exclusions
[[headers]]
  for = "/src/assets/images/hero-eyeglass.png"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Netlify-No-Transform = "true"

[[headers]]
  for = "/src/assets/images/product-overview.gif"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Netlify-No-Transform = "true"

[[headers]]
  for = "/src/assets/videos/editedTSonic.mp4"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Netlify-No-Transform = "true"

[[headers]]
  for = "/src/assets/images/background.png"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Netlify-No-Transform = "true"

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Netlify-No-Transform = "true"

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Netlify-No-Transform = "true"

# Preserve styles.css specifically
[[headers]]
  for = "/src/styles.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
    X-Netlify-No-Transform = "true"
    Content-Type = "text/css"

# Function for bypassing asset optimization
[functions]
  directory = "netlify/functions"
